Repository googleapis/python-spanner-sqlalchemy, pull requests merged in 2021-12, with the labels that each got.

#159 fix: raise Unimplemented error when creating temporary tables
  README.md
  google/cloud/sqlalchemy_spanner/provision.py
  google/cloud/sqlalchemy_spanner/requirements.py
  google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
  test/test_suite.py
Labels: cla: yes, api: spanner

#160 fix: calculate limit value correctly for offset only queries
  google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
  test/test_suite.py
Labels: cla: yes, api: spanner

#161 test: increase the package testing coverage
  google/cloud/sqlalchemy_spanner/_opentelemetry_tracing.py
  google/cloud/sqlalchemy_spanner/provision.py
  google/cloud/sqlalchemy_spanner/requirements.py
  google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
  noxfile.py
  test/test_suite.py
Labels: cla: yes, automerge, api: spanner

#135 feat: support JSON data type
  google/cloud/sqlalchemy_spanner/requirements.py
  google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
  test/test_suite.py
Labels: cla: yes, type: feature request, api: spanner

#155 docs: update benchmarks
  BENCHMARKS.md
Labels: cla: yes, api: spanner

#162 chore: add release please config
  .github/release-please.yml
Labels: automerge, api: spanner

#158 test: add base class for the Spanner specific tests
  test/test_suite.py
Labels: cla: yes, api: spanner

#164 refactor: update default user agent header to match convention
  google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
  test/test_suite.py
Labels: api: spanner

#165 chore: setup release 1.0.0
  README.md
  setup.cfg
  setup.py
  version.py
Labels: api: spanner

#166 chore: remove unused docs-presubmit
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
Labels: automerge, api: spanner

#171 fix: bump up google-cloud-spanner required version
  setup.py
Labels: type: process, api: spanner

#173 fix: NOT NULL computed column creation failure
  google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
  test/test_suite.py
Labels: api: spanner

#178 Update README.md
  README.md
Labels: api: spanner

#180 docs: add a README section for the autoincremented ids
  README.md
Labels: documentation, api: spanner

#182 docs: explicitly recommend uuid to generate PKs
  README.md
Labels: automerge, api: spanner

#175 chore: auto-assign issues to new Spanner owner
  .github/blunderbuss.yml
Labels: automerge, api: spanner
