Repository googleapis/python-spanner-sqlalchemy, pull requests merged in 2022-09, with the labels that each got.

#241 fix: Spanner auto managed indexes should not be introspected
  google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
  test/test_suite_13.py
  test/test_suite_14.py
Labels: type: bug, api: spanner

#244 fix: don't introspect internal UNIQUE constraints
  create_test_database.py
  google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
Labels: type: bug, api: spanner

#245 docs: mention package install with pip
  README.rst
Labels: api: spanner

#243 docs: add auto retry mechanism explanation
  README.rst
Labels: type: docs, api: spanner

#250 fix: adding requirements
  .kokoro/build.sh
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/requirements.in
  .kokoro/requirements.txt
  requirements.in
  requirements.txt
Labels: api: spanner
